class Unexpected_response( Exception ):
    pass
